site_name: Pesquisa - Apache Spark com Delta Lake e Apache Iceberg
repo_url: https://github.com/thomasjefersonm/pesquisadados
nav:
  - Contextualização: index.md
  - Apache Spark (PySpark): spark.md
  - Delta Lake: delta.md
  - Apache Iceberg: iceberg.md
theme: readthedocs
edit_uri: edit/main/docs/
